version: "3"
  
networks:
  proxy-network:
    external: true

volumes:
  flame:

secrets:
  password:
    file: "./secrets/flame_password"

services:
  flame:
    image: "pawelmalak/flame:latest"
    container_name: "flame"
    restart: "unless-stopped"
    networks:
      - "proxy-network"
    volumes:
      - "flame:/app/data"
    secrets:
      - "password"
    environment:
      - "PASSWORD_FILE=/run/secrets/password"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flame.rule=Host(`${FLAME_HOST}`)"
      - "traefik.http.routers.flame.tls.certresolver=letsencrypt"
